apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 2
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: '5.5-slim'
  licenseKeySecretName: hazelcast-license-key
  exposeExternally:
    type: Smart
    discoveryServiceType: NodePort
    memberAccess: NodePortExternalIP